modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/FirEmerald/FECore/issues"
[[mods]]
modId="fecore"
version="${file.jarVersion}"
displayName="FECore"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/FirEmerald/FECore"
logoFile="logo.png"
#credits=""
authors="FirEmerald"
description='''Provides shared code for FirEmerald's Minecraft mods'''
[[dependencies.fecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
	